# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d846775f9e6f2468fab93c8285aad0e1abf7e894190627ba8ca65a7b65bee38f1df899c528f29960e3fa22f42513b03e538a6c51e406b45118f5cd87dc61c46c

test:
  secret_key_base: 279147ec7773cbf5306a51a4097d010b1af24b6874e0403c40d727ff29adfd381d8be26569d5675202d1f53663405b8ebb2b5e803f4a30fcc3001236810aa8d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
